### ISSUE TITLE
Game Size Calculation for Non-Installed Titles occasionally stops on random games

### ISSUE THREAD

**Issue by cnapolit** [Jeshibu/PlayniteExtensions#10]
While attempting to calculate for non-installed games, the Calculator will sometimes prematurely end on random titles.
Re-attempting to calculate will consistently end in the same manner for the same game.
Logs have no mention of any exception handling or indications of failure.
One example that consistently failed was the steam version of Amnesia: Rebirth.

**Comment by cnapolit** [comment]
[extensions.log](https://github.com/Jeshibu/PlayniteExtensions/files/9440278/extensions.log)
[playnite.log](https://github.com/Jeshibu/PlayniteExtensions/files/9440279/playnite.log)

**Comment by cnapolit** [comment]
Just noticed it proc on Transformers: Fall of Cybertron, which I know is delisted from Steam. Probably related.

**Comment by Jeshibu** [comment]
Added more robust error handling in the latest release. If there are games that repeatedly error out or if there are repeated errors in general let me know.
