### ISSUE TITLE
game size calculation could not find part  of the path 

### ISSUE THREAD

**Issue by Kdog88** [Jeshibu/PlayniteExtensions#11]
[config.zip](https://github.com/Jeshibu/PlayniteExtensions/files/9484940/config.zip)

Game size calculation could not find  part of the path for a game jolt game....even though it was clearly downloaded on my ssd in my laptop

**Comment by Jeshibu** [comment]
04-09 10:20:11.194|INFO |GamesSizeCalculator#GamesSizeCalculator:Updated Steam version field from 006.387 GB to 006.292 GB
04-09 10:20:14.253|INFO |GamesSizeCalculator#GamesSizeCalculator:Updated Steam version field from 006.387 GB to 006.292 GB
04-09 10:20:15.014|ERROR|GamesSizeCalculator#GamesSizeCalculator:Error while getting directory size in C:\Users\johna\AppData\Local\game-jolt-client\User Data\Default\Games\USHF-438466\Ultimate Sonic Heroes Fighters - Definitive Edition-692434 of game Ultimate Sonic Heroes Fighters
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\johna\AppData\Local\game-jolt-client\User Data\Default\Games\USHF-438466\Ultimate Sonic Heroes Fighters - Definitive Edition-692434\data\USHF\Ultimate Sonic Heroes Fighters - Definitive Edition\reshade-shaders\Shaders\CorgiFX\StageDepthPlus with depth buffer modification'.

**Comment by Jeshibu** [comment]
Issue was long paths. Should be fixed now.
