### ISSUE TITLE
[Game Size Calculator] Incorrect size being returned

### ISSUE THREAD

**Issue by Jhanlon95** [Jeshibu/PlayniteExtensions#12]
**Bug Description**
Checked Steelrising's size within Playnite and it's being reported as around 15GB, but when checking it within Steam's local files itself it's being reported as 67GB. Spoke to Jeshibu and he asked me to raise it as he was also experiencing the same issue

![image](https://user-images.githubusercontent.com/11045596/189547752-7c090e11-1ef7-4723-bf7d-34e96fea0330.png)

**To Reproduce**
Get the size for Steelrising, it won't match the size from Steam

**Logs**
[playnite.log](https://github.com/Jeshibu/PlayniteExtensions/files/9543483/playnite.log)
[extensions.log](https://github.com/Jeshibu/PlayniteExtensions/files/9543484/extensions.log)

**Comment by Jeshibu** [comment]
Thanks for bringing this to my attention! Fixed in 1.27.
