### ISSUE TITLE
Steam Tags Importer: Fails when trying to scrape data in English

### ISSUE THREAD

**Issue by forenta** [Jeshibu/PlayniteExtensions#13]
Playnite 9.19
Steam Tags Importer 3.2

I had wondered about the plugin running on my one device but not the other. Now I found the setting that causes the problem: when I set 'tag language' to 'English' or 'don't specify', the extension crashes as seen in the screenshot. If I set it to German (my native language), I get the tags.
But I would like to have them in English to avoid confusion of the different sources.

![screen](https://user-images.githubusercontent.com/2451238/189975258-b5be0608-0bfc-4e78-95f7-f7b6423b3682.jpg)

**Comment by Jeshibu** [comment]
Thanks for reporting this. I can't reproduce it. Could you share the `extensions.log` file (or relevant messages from it) located in the folder that opens when you, in Playnite, open the main menu > `About Playnite` > `Other` (tab) > `User data directory` ?

**Comment by forenta** [comment]
Thanks for your fast 
Indeed: I switched the language on my tablet device and it worked without issues. Again on my Desktop, it's only working when set to German. Weird thing.
`extensions.log` didn't recorded anything, but here's a bit from `playnite.log`:

`12-09 17:20:10.339|ERROR|GameEditViewModel:Failed to download metadata, 96e8c4bc-ec5c-4c8b-87e7-18ee5a690626, arrog_trove
System.NotSupportedException: Von diesem CollectionView-Typ werden keine Änderungen der "SourceCollection" unterstützt, wenn diese nicht von einem Dispatcher-Thread aus erfolgen.
   bei System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bei System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   bei System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   bei System.Collections.ObjectModel.Collection`1.Add(T item)
   bei SteamTagsImporter.SteamTagsGetter.GetSteamTags(Game game, Boolean& newTagsAddedToSettings) in D:\code\Jeshibu\PlayniteExtensions\source\SteamTagsImporter\SteamTagsGetter.cs:Zeile 24.
   bei SteamTagsImporter.SteamTagsMetadataProvider.GetTags(GetMetadataFieldArgs args) in D:\code\Jeshibu\PlayniteExtensions\source\SteamTagsImporter\SteamTagsMetadataProvider.cs:Zeile 25.
   bei Playnite.DesktopApp.ViewModels.GameEditViewModel.<>c__DisplayClass482_0.<DownloadPluginData>b__0(GlobalProgressActionArgs args) in C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\GameEditViewModelMetadata.cs:Zeile 483.
   bei Playnite.ViewModels.ProgressViewViewModel.<ActivateProgress>b__31_0() in C:\projects\playnite\source\Playnite\ViewModels\ProgressViewViewModel.cs:Zeile 122.`

**Comment by Jeshibu** [comment]
Thanks! To be clear, the only language you're switching here is the one in the Steam Tags Importer settings, right?

**Comment by forenta** [comment]
> Thanks! To be clear, the only language you're switching here is the one in the Steam Tags Importer settings, right?

Exactly.

**Comment by Jeshibu** [comment]
Hey, sorry I couldn't reproduce this still. I've since added (most of) this plugin's functionality to the Steam library and metadata plugins. Could you check if it works there?
