### ISSUE TITLE
"No Legacy Games games found" - just installed

### ISSUE THREAD

**Issue by dpuza** [Jeshibu/PlayniteExtensions#14]
I just installed this extension but it won't update my Playnite games list with any Legacy games even though I've followed the instructions, logged into the Legacy Games client and installed a game:

![image](https://user-images.githubusercontent.com/4071161/193815988-07470ab8-9ef1-4527-8a03-8ae5d8fd8906.png)

![image](https://user-images.githubusercontent.com/4071161/193816028-034b005e-2c8b-4158-97dd-528c7368ecda.png)

**Comment by Jeshibu** [comment]
The file structure of `%appdata%\legacy-games-launcher\app-state.json` changed with the new client (1.6.4). Just released plugin version 0.3 in which this should be fixed.
