### ISSUE TITLE
Games Size Calculator: Error due to path length

### ISSUE THREAD

**Issue by Mellified** [Jeshibu/PlayniteExtensions#16]
Games Size Calculator shows this error every time it is run. Most likely because the path is longer than the default Windows path limit - which can be disabled in Windows 10 and newer.

![image](https://user-images.githubusercontent.com/81110968/195909995-1251ca14-85e9-448a-a37b-b9244264c262.png)

**Comment by Jeshibu** [comment]
This used to be Games Size Calculator functionality, but darklinkpower has since folded it into Playnite 10. Games Size Calculator now only fetches install sizes online from Steam and GOG for games that aren't installed.
