### ISSUE TITLE
Can Playnite sync into RAWG?

### ISSUE THREAD

**Issue by profucius** [Jeshibu/PlayniteExtensions#18]
I can't seem to find any information anywhere of how to sync into RAWG other than the storefronts they offer directly. Do you think this would be possible by any measure?

**Comment by Jeshibu** [comment]
You can as of the RAWG Library plugin 0.2! Once you've updated your plugin, log in in the plugin settings, check your mappings in the other tabs, and save. Then, select and right click some (or all) games and click "Sync to RAWG".
