### ISSUE TITLE
Add "None" as an option within Mapping to RAWG settings

### ISSUE THREAD

**Issue by profucius** [Jeshibu/PlayniteExtensions#20]
I just tested the new version 0.2 feature to Sync to RAWG. It seems to work great! However, I've noticed that if any game(s) have a null value within the Completion field (i.e. blank field), the addon skips that game during sync. Unfortunately, there is no way to know this happened, as the addon doesn't notify the user that any games were skipped after syncing is done (another good idea to implement).

I propose adding an entry in the Mapping to RAWG settings tab, to offer "None" to be mapped to the user's choice. I.e. if the game has nothing set in the field for Completion, it can still be mapped to perhaps "Not Played" within RAWG due to this added feature.

Hopefully you can see the value of this, especially in a library as large as mine (1300+ games) it would be insurmountably tedious to manually review each game's completion status before syncing it to RAWG. Thanks!

**Comment by Jeshibu** [comment]
"None" as a used completion status seems weird to me. You can't set it via the right click menu (though I guess you can via the edit window). You could filter your library to completion status: none, and then select them all, right click, edit, and set the completion status there. That would do it in one fell swoop.

**Comment by profucius** [comment]
Well the issue is that I was required to rebuild my Playnite installation, which caused me to lose all of my metadata such as Completion status on games that I have played/completed. I don't have the time to manually review all of the details for each game, and if I batch update all of them to a tag then it will still require me to fix each one of those. At least by being able to assign None in Playnite to Uncategorized in RAWG, the games will be in RAWG now and I will not have written inaccurate data to those games.

If you still do not see the value in the feature, would you be willing to add a feature such as generating a log after sync completes of any games that were not synced due to a missing Completion status. This way at least I know which ones to address. Even better, although probably a tad more complicated, automatically add a Tag to those games such as "Not synced to RAWG"

**Comment by Jeshibu** [comment]
Could you beta test the new release? This should fix both your issues, but the auto-syncing might still have some other overlooked issues.
https://github.com/Jeshibu/PlayniteExtensions/releases/tag/rawg0.3
Install by downloading and opening with or dragging onto Playnite.

**Comment by Jeshibu** [comment]
woops didn't mean to close

**Comment by Jeshibu** [comment]
Should be in as of 0.3.1.
Keep in mind that I can't give imported games the status None, so you'll have to make that the default new game status in the ctrl+W menu, and select Default for that RAWG status.
