### ISSUE TITLE
Unable to sync Wishlist from RAWG to Playnite

### ISSUE THREAD

**Issue by profucius** [Jeshibu/PlayniteExtensions#22]
Ok I have ran some tests from our previous ticket, and am still having an issue with Wishlist items from RAWG importing to Playnite. I've recorded a video demonstrating my steps and the result. Github wont allow direct uploading, so I've uploaded to Imgur:

https://imgur.com/A0h4dXz

Notes: The video shows Honkai as an example game, which I have never added to RAWG prior, nor added to Playnite library. The Playnite filters are all clear except for the Library field being set to RAWG.

**Comment by profucius** [comment]
Alright here is what I've done. I had a whole mess of stuff in my logs from previous testing, so I removed the `extensions.log` and `playnite.log` files, let Playnite recreate them clean, and then I activate to Playnite menu > Update Library > RAWG. These are all that shows within these two files immediately afterwards. I do not see any API Keys in the logs, so perhaps I didn't do this correctly? I'll try again if you wish. I'm a power user so don't worry about giving me some complex steps if needed.

extensions.log
`28-11 14:32:53.366|DEBUG|GamePassCatalogBrowser#Downloader:Downloading string from https://catalog.gamepass.com/sigls/v2?id=fdd9e2a7-0fee-49f6-ad69-4354098401ff&language=en-us&market=US with method GET
28-11 14:32:53.366|DEBUG|GamePassCatalogBrowser#Downloader:Downloading string from https://catalog.gamepass.com/sigls/v2?id=1d33fbb9-b895-4732-a8ca-a55c8b99fa2c&language=en-us&market=US with method GET
28-11 14:32:53.541|INFO |CheckDlc#PluginDatabaseObject`4:Task Refresh() - 00:00.06 for 0/0 items
28-11 14:32:53.622|INFO |HowLongToBeat#PlaynitePlugin`1:Task OnLibraryUpdated() - 00:00.06 for 0/0 items
28-11 14:32:53.696|INFO |SuccessStory#PluginDatabaseObject`4:Task Refresh() - 00:00.05 for 0/0 items
28-11 14:32:53.715|DEBUG|SteamTagsImporter#SteamTagsImporter:Library update: 0 games
28-11 14:32:53.777|DEBUG|SteamTagsImporter#SteamTagsImporter:Adding tags to 0 games
`
playnite.log
`28-11 14:32:51.494|INFO |MainViewModelBase:Importing games from RAWG plugin.
28-11 14:32:51.752|INFO |MainViewModelBase:Starting Library Install Size scan
28-11 14:32:51.782|INFO |MainViewModelBase:Finished Library Install Size scan
28-11 14:32:52.792|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 952d77f3-b569-437b-9561-27b464359975
28-11 14:32:52.865|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 952d77f3-b569-437b-9561-27b464359975, True
28-11 14:32:52.884|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: e1d132a2-c0eb-4c0b-9d85-40ba258eda1c
28-11 14:32:53.122|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: e1d132a2-c0eb-4c0b-9d85-40ba258eda1c, True
28-11 14:32:53.165|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: ac3bd702-a25e-41d5-a846-64d24a29d343
28-11 14:32:53.333|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: ac3bd702-a25e-41d5-a846-64d24a29d343, True
28-11 14:32:53.357|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 2d4f711e-d039-474b-8537-ab9c7bb49133
28-11 14:32:53.387|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 2d4f711e-d039-474b-8537-ab9c7bb49133, True
28-11 14:32:53.479|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 4d8fa824-d647-4df7-ab6b-e7620ac06e63
28-11 14:32:53.541|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 4d8fa824-d647-4df7-ab6b-e7620ac06e63, True
28-11 14:32:53.558|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: f1b11814-0e7c-43f3-89fc-74f9a0feb11c
28-11 14:32:53.622|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: f1b11814-0e7c-43f3-89fc-74f9a0feb11c, True
28-11 14:32:53.638|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 4e5bfda7-1484-49d1-9a38-63232d50b411
28-11 14:32:53.696|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 4e5bfda7-1484-49d1-9a38-63232d50b411, True
28-11 14:32:53.715|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 2abaec01-f909-4bda-9776-d2d901e1418a
28-11 14:32:53.777|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 2abaec01-f909-4bda-9776-d2d901e1418a, True
`

**Comment by Jeshibu** [comment]
Looks like it's not set to import anything. On the first page of the plugin settings, do you have "Import user library" checked?

**Comment by profucius** [comment]
> Looks like it's not set to import anything. On the first tab of the plugin settings, do you have "Import user library" checked?

I just updated my post with additional steps I attempted, to clarify

**Comment by Jeshibu** [comment]
Yes, it imports games, and it doesn't care if they exist already. If you want to only import RAWG wishlist games, set the other RAWG statuses to "Do not import".
I'll have a think on importing completion statuses and user ratings only, or maybe doing that for games that exist and adding games that don't exist.
As a workaround, you can use DuplicateHider in the meantime, though it won't update statuses for existing games.

**Comment by profucius** [comment]
Ahh, okay that makes sense! I didn't even see the "Do not import" option within those (I have too many statuses, and had to scroll haha). For my use-case, importing only Wishlist is perfect.

I just tested it, and it does work now! However, and perhaps this belongs in a separate ticket, is there anything on the roadmap for importing only one copy of each game? Perhaps a "preferred" platform could be set. I can use DuplicateHider in the meantime, although it does still require manually setting my preferred "main" platform of each set of duplicates, which could be prevented with aforementioned idea.

**Comment by Jeshibu** [comment]
Are you getting duplicates that are both from the RAWG library, or do you just mean that the end state of your library is that you have duplicates?

**Comment by profucius** [comment]
Yeah I should clarify: After taking your advice, going into Mapping from RAWG, setting everything to "Do not import" except for Wishlist, I am now not importing any games except for RAWG Wishlist games. Those games are not importing as duplicate entries, but they show up under multiple platforms, as your library addon assigns all Platforms that the game exists within. It would be nice to have a feature to restrict that to just a specific one (or perhaps a select multiple) preferred platforms as it imports to Playnite.

**Comment by Jeshibu** [comment]
Unfortunately while RAWG's APIs do return a field for what platform you own a game on, it is always empty I have not found a way to set it. I think they've abandoned that functionality.

While I could make a ranked order of platforms that newly imported games would pick the first match of, it would also disable some valid multiplatform titles like Xbox One + Xbox Series X/S, or PS4+5.

**Comment by Jeshibu** [comment]
BTW every game there is a single game, but because it's grouped by a multi-value field like platform, it's displayed multiple times each.

**Comment by profucius** [comment]
Ah interesting, ok I see. Well then that is no worry. I will create a saved filter of imported RAWG games, and make it a recurring manual action to handle their platforms every so often. I don't add too many games to my Wishlist, so it's not hard to keep up with. Thanks for the consideration though!
