### ISSUE TITLE
Does RAWG API provide syncing into Collections, and game rankings?

### ISSUE THREAD

**Issue by profucius** [Jeshibu/PlayniteExtensions#23]
Hey again, I was thinking about what other data might be available via the API from RAWG. Do you know if any of these could be integrate-able?

1. Collections. You've already integrated syncing _FROM_ collections, is it possible to sync _TO_ them (Playnite into RAWG) as well? This could simply be a right-click menu option. Collections could be refreshed from the addons settings, as it is already offered.

2. The "# Top YEAR" which shows at the top of a game listing. e.g. "#216 Top 2019" could be synced to Playnite as "2019 #216" which could allow it to be sortable within Playnite views.

Scenarios:
- Add games from Playnite into a RAWG collection for your own GOTY picks.
- Sort/filter games within Playnite based on the RAWG game ranking for a specific (or all) year.

Given that Playnite doesn't (yet, I hope in the future) offer custom fields, perhaps it's possible to sync one or all of these into the Categories field, or Tags, or another of the user's choice.

Just thinking out loud here, if these aren't available in the RAWG API then that's a bummer but understandable.

**Comment by Jeshibu** [comment]
First sounds like a good idea. Second, I'm not sure. You would sync them as `2019 #216` to what field?

**Comment by profucius** [comment]
Personally, I use my unused fields for other purposes, so I would probably use the Series or Age Rating field. But I imagine it could be a selection box in the addon settings that lets the user pick where to store that data.

I would understand if you wanted to put a pin in this idea, if it were to be to complex to add that. I really want Josef and/or whoever helps to eventually give us Custom Fields within Playnite, then a field could be dedicated to "RAWG Ranking" etc etc.

But either way, I'm glad you can see value in the syncing Collections to RAWG idea. I can think of multiple uses for this!

**Comment by Jeshibu** [comment]
The collections are implemented, but I'm not sold on the ranking idea, so I'm closing this.
