### ISSUE TITLE
[itch.io Bundle Tagger] Option to select bundles to tag

### ISSUE THREAD

**Issue by chocolatechipcats** [Jeshibu/PlayniteExtensions#24]
If a user prefers to only tag the bundles they own, they need to keep deleting the unwanted ones in library manager. It would be helpful to be able to disable them in the extension options, perhaps with a checkbox for each bundle. 

As the bundles aren't done _too_ often, hopefully this wouldn't be too much time to maintain.

Thanks.

**Comment by Jeshibu** [comment]
Done now.
