### ISSUE TITLE
[LaunchBox] Resize Non-Square Icons

### ISSUE THREAD

**Issue by sgern** [Jeshibu/PlayniteExtensions#28]
Currently, if an icon from Launchbox isn't perfectly square, it won't line up with other square icons in Details View and the game title will either be pulled left or pushed right.

Would it be possible for the extension to vertically compress too-wide icons and horizontally compress too-tall icons, then align/center the result so the game title stays in line with others?

**Comment by Jeshibu** [comment]
Added an option to extend any image to square (default setting for icons for new users).
