### ISSUE TITLE
[MobyGames Metadata] Feature Request: Ability to use bulk functionality for selected or filtered games only.

### ISSUE THREAD

**Issue by HerrKnarz** [Jeshibu/PlayniteExtensions#32]
At the moment the batch functionality to add groups/genres always tries to download data for all games in the library. I'd rather be able to apply the bulk updates only to selected or filtered games, because I don't really need those tags for all my games, but only the ones I plan to play. That would reduce unnecessary traffic and loading times.

**Comment by Jeshibu** [comment]
I don't think it would, the process is now:
- Download all games
- Match them with games in your Playnite library

There's no practical way to limit the games you download to only the games in your selection/library that I can think of. You could limit which games you match, which would speed that bit up.

**Comment by Jeshibu** [comment]
Gonna close this since it's not a solution to the proposed problem.
