### ISSUE TITLE
[Launchbox] Missing boxarts

### ISSUE THREAD

**Issue by Negerhoran** [Jeshibu/PlayniteExtensions#33]
I'm trying to download box art for my N64 games and SNES games, but only a fraction of the available artworks end up in the search results.
is the "Region" selector borked?
For example, my N64 games only receive Japanese box art.

**Comment by Jeshibu** [comment]
Can you post a screenshot of your Launchbox metadata cover settings, and name/link some games that it's not working for?

**Comment by Negerhoran** [comment]
You can mark this as resolved. After hours of work I realized that you can specify the orientation of the artwork, and that the N64 box art count as "landscape".
Sorry for bothering you.

**Comment by Jeshibu** [comment]
Alright, glad to hear it's working for you!
