### ISSUE TITLE
Want PS3/PS4 cover for Steam game using Launchbox

### ISSUE THREAD

**Issue by syaifulnizamyahya** [Jeshibu/PlayniteExtensions#35]
I have Alien Isolation in Steam. Instead of Steam cover(without any overlay), I want PS3 or PS4 cover for the game (cover with Playstation 3/Playstation 4 overlay).

For this:

1. I set Alien Isolation Platform as Playstation 3/Playstation 4
2. The library remains as Steam
3. I fetch cover for this game using both Launchbox.

Unfortunately, the cover that I get is Alien Isolation cover without Playstation 3/Playstation 4 overlay.

I checked in Launchbox games db, I can see Alien Isolation have Playstation 3/Playstation 4 cover. Why does Launchbox does not get the Playstation 3/Playstation 4 cover for this game? This does not happen for all games. Certain games Im able to get Playstation 3/Playstation 4 cover, while certain game I cant.

**Comment by Jeshibu** [comment]
Just tried to reproduce and it works as expected. I think your covers/regions settings aren't letting the cover through.

**Comment by syaifulnizamyahya** [comment]
Finally figured it out and got it working. Increase the max size of the cover.
![image](https://github.com/Jeshibu/PlayniteExtensions/assets/10744241/7f3e10f4-f258-4e99-960b-39b2661a3301)

**Comment by Jeshibu** [comment]
Sorry, forgot to mention this, but that field should absolutely not influence image selection, it's for resizing purposes only. Let me know if it skips anything (specifically which images for which games) if you set it down to a reasonable size like 600x900.
