### ISSUE TITLE
[MobyGames Metadata] (Feature Request) Consider platform when importing game data

### ISSUE THREAD

**Issue by shakeyourbunny** [Jeshibu/PlayniteExtensions#36]
Hi,

does the MobyGames Metadata Import extension consider the platform on importing release dates?

Some games have a long list of different release dates, depending on the platform, often there IBM-PC ports got later on it than the original release, but the extension does import the most old date regardless of platform.

Perhaps this should be an toggleable option if it should just get the oldest date or the correct one.

Sample games:
https://www.mobygames.com/game/50/zork-the-great-underground-empire/ (released on the PDP-10 in 1980, but on IBM-PC 1984)
https://www.mobygames.com/game/12111/ultima-i/ (released on Apple II in 1986, IBM-PC 1986 or 1987)
https://www.mobygames.com/game/1823/california-games/ (original release in 1987, IBM-PC release 1988)

**Comment by Jeshibu** [comment]
Is an option in the settings as of 0.5.1
