### ISSUE TITLE
[Xbox metadata] Does not return anything in search

### ISSUE THREAD

**Issue by L3chuso** [Jeshibu/PlayniteExtensions#39]
Hello,

A couple of days ago the xbox metadata plugin does not return anything in the searches. It only sometimes returns Xbox 360 games nothing else.

I am attaching the log, since it performs the search correctly, but on the web it says that it has not found anything.

`12-08 16:08:06.702|INFO |XboxMetadata#WebDownloader:Call to https://marketplace.xbox.com/en-US/Search?query=A%20Short%20Hike&DownloadType=Game completed in 00:00:02.5193322
12-08 16:08:14.822|INFO |XboxMetadata#WebDownloader:Call to https://www.microsoft.com/msstoreapiprod/api/autosuggest?market=en-US&sources=xSearch-Products&filter=+ClientType:StoreWeb&counts=20&query=A%20Short%20Hike completed in 00:00:10.6399418
12-08 16:11:22.315|DEBUG|NewsViewer#ProcessStarter:Opening URL: https://steamdb.info/app/1055540/graphs/
12-08 16:17:11.127|DEBUG|Extras#Extras:Pushed "Vista detallada - A Plague Tale: Innocence"
12-08 16:17:11.629|DEBUG|NewsViewer#Downloader:Downloading string from https://store.steampowered.com/feeds/news/app/752590/l=spanish with method GET
12-08 16:17:11.629|DEBUG|NewsViewer#Downloader:Downloading string from https://api.steampowered.com/ISteamUserStats/GetNumberOfCurrentPlayers/v1/?appid=752590 with method GET
12-08 16:17:12.669|DEBUG|Extras#Extras:Pushed "Vista detallada - A Plague Tale: Requiem"
12-08 16:17:18.153|INFO |XboxMetadata#WebDownloader:Call to https://marketplace.xbox.com/en-US/Search?query=A%20Plague%20Tale%3A%20Requiem&DownloadType=Game completed in 00:00:02.3211963
12-08 16:17:26.472|INFO |XboxMetadata#WebDownloader:Call to https://www.microsoft.com/msstoreapiprod/api/autosuggest?market=en-US&sources=xSearch-Products&filter=+ClientType:StoreWeb&counts=20&query=A%20Plague%20Tale%20Requiem completed in 00:00:10.6403729
12-08 16:17:30.585|DEBUG|Extras#Extras:Pushed "Vista detallada - Age of Empires III: Definitive Edition"
12-08 16:17:33.470|INFO |XboxMetadata#WebDownloader:Call to https://www.microsoft.com/msstoreapiprod/api/autosuggest?market=en-US&sources=xSearch-Products&filter=+ClientType:StoreWeb&counts=20&query=Age%20of%20Empires%20III%20Definitive%20Edition completed in 00:00:00.1767513
12-08 16:17:33.730|INFO |XboxMetadata#WebDownloader:Call to https://marketplace.xbox.com/en-US/Search?query=Age%20of%20Empires%20III%3A%20Definitive%20Edition&DownloadType=Game completed in 00:00:00.4368708
12-08 16:17:41.739|INFO |XboxMetadata#WebDownloader:Call to https://marketplace.xbox.com/en-US/Search?query=Age%20of%20Empires%3A%20Definitive%20Edition&DownloadType=Game completed in 00:00:02.1146105
`

**Comment by Jeshibu** [comment]
Thanks for reporting! This is fixed as of version 0.3.1.
