### ISSUE TITLE
MobyGames: Batch metadata download failing to match games on database

### ISSUE THREAD

**Issue by darklinkpower** [Jeshibu/PlayniteExtensions#44]
It seems that it fails to match them even if they have the same name. One example of this is Chrono Trigger, whose only difference is that the game name on Playnite is all caps

![image](https://github.com/Jeshibu/PlayniteExtensions/assets/1389286/2ae63f90-1a4d-48ba-a1f8-c59b00dd808b)

Another example is Gears of War 4, which is an exact match:

![image](https://github.com/Jeshibu/PlayniteExtensions/assets/1389286/b57d78b0-cdf2-405d-9803-f1d40910c528)

**Comment by Jeshibu** [comment]
These are failing to be matched because there is no platform overlap between the Playnite game and the Moby Games game. I could make "Windows Apps" turn into "PC (Windows)" I guess, but the Chrono Trigger one is working as it should in my opinion.
