### ISSUE TITLE
[Legacy Games] JSON Serialisation error on importing games

### ISSUE THREAD

**Issue by WhoIsMoloBartell** [Jeshibu/PlayniteExtensions#46]
Hi,

Very useful extension for a terrible launcher. Thanks for your effort.

Game is installed in LL, but I get the image error (enclosed). I have attached relevant log for your convenience.

Thanks

![image](https://github.com/Jeshibu/PlayniteExtensions/assets/103775859/89030547-a367-4475-adb6-ae113edb3b90)

[extensions.log](https://github.com/Jeshibu/PlayniteExtensions/files/12707006/extensions.log)

[playnite.log](https://github.com/Jeshibu/PlayniteExtensions/files/12707007/playnite.log)

**Comment by Jeshibu** [comment]
Thanks for reporting! Could you send me your `%APPDATA%\legacy-games-launcher\app-state.json` file? There is personal information in it, so if you post it publicly here you might want to redact it in the way I describe here: https://github.com/Jeshibu/PlayniteExtensions/issues/9

Alternatively you can send it to me on Discord, same username.

**Comment by WhoIsMoloBartell** [comment]
Hi, i've sent you a friend request on Discord

**Comment by Jeshibu** [comment]
Fixed in 0.6.1

**Comment by WhoIsMoloBartell** [comment]
Confirmed as fixed. Thanks :)
