### ISSUE TITLE
[Launchbox Metadata] Doesn't download Cover Image/possibly other images for Japan region

### ISSUE THREAD

**Issue by TheT113** [Jeshibu/PlayniteExtensions#47]
For games released only in Japan, it fails to download any Cover Image at all. I believe it also doesn't download Fan Art (or Screenshots? I'm not sure when/if it does this in general) for Background Images.

**Comment by Jeshibu** [comment]
Did you configure those to be enabled under `main menu > Add-ons > Extension settings > Metadata Sources > LaunchBox` under their respective tabs?

**Comment by TheT113** [comment]
I meant to look for the settings and thought I did, but I forgot...

Still, I'm looking at it now and I'm confused. All the regions are checked. I'm not sure what the "Alias" means. But I have imported games that only have a single region, Japan, and it imports no image at all. Possible the issue is the "Orientation" option on the Covers tab? I'm going to change to Any and see if that fixes it.

**Comment by TheT113** [comment]
Yeah, some combination of this + the minimum image sizes must have done it. Sorry about that.

**Comment by Rings4** [comment]
> Yeah, some combination of this + the minimum image sizes must have done it. Sorry about that.

Thank you so much for this hint, I was also only getting Japanese box art and it turns out it was also because the orientation was set to "Vertical"! I fixed it by setting it to "Any" since N64 games are Horizontal.
