### ISSUE TITLE
GoG metadata is not working correctly.

### ISSUE THREAD

**Issue by JNx66** [Jeshibu/PlayniteExtensions#49]
Hey Hi. I'm adding only GoG games into Playnite. I notice a lot of games are not found.

Going a little deeper, I see that the games that are not found are games that are not in the GoG store [Baldur's Gate: The Original Saga](https://www.gogdb.org/product/1207658886) however it was superseded by [Baldur's Gate: Enhanced Edition](https://www.gogdb.org/product/1207666353). I'm interested to add "Baldur's Gate: The Original Saga" not the "Enhanced Edition", if you notice from the GoGDB site in the detail tab, you have the cover and the information need it to add it in the library, which use the GoG API, but the add-ons can't find it.

Another problem I notice are games that the product type is "Package" and not "Game" aren't found either, look for instance [Fallout](https://www.gogdb.org/product/1440166342) or [Pillars of Eternity: Definitive Edition](https://www.gogdb.org/product/1344895033)

There is a workaround to fix this? beside adding the information manually. thank you

https://www.gogdb.org/moreinfo

**Comment by Jeshibu** [comment]
Packages are included since the January 0.2 release. I'm not sure about including delisted games if it means switching data source to GOG DB's data files. The examples listed don't really seem pressing to me at least.
