### ISSUE TITLE
Launchbox database not working anymore

### ISSUE THREAD

**Issue by Steveneska** [Jeshibu/PlayniteExtensions#50]
Since there was an update to the Launchbox database, the add-on doesn't work anymore, throwing a `Failed to download metadata: Object reference not set to an instance of an object error` when trying to download a game metadata.

**Comment by Jeshibu** [comment]
What version number are you on? 0.6.4 was released yesterday.

**Comment by Steveneska** [comment]
I was running 0.6.3 and after updating to 0.6.4 it fixed the issue I was experiencing
