### ISSUE TITLE
Import "Community Rating Count" from LaunchBox Database

### ISSUE THREAD

**Issue by MotherSoraka** [Jeshibu/PlayniteExtensions#51]
If Playnite doesn't natively support for such a attribute, can we atleast somehow import this number as a different unused attribute such as "Tag" or "User Score" for example or just anything, so we can sort or filter out the games based on the "Community Rating Count"?

**Comment by Jeshibu** [comment]
The only usable field for this would be the version field I think. User score is out because it can't handle values over 100. Tags would just get your tags spammed with `Community rating count: 156` and `Community rating count: 682` etc, without the ability to sort by them.

**Comment by Jeshibu** [comment]
Version field apparently can't be set by a metadata provider, so this isn't doable for now.
