### ISSUE TITLE
Legacy Games library integration issue

### ISSUE THREAD

**Issue by wolfrik17** [Jeshibu/PlayniteExtensions#6]
Getting this error:
Failed to get Legacy Games games: Value cannot be null. Parameter name: source

Legacy games launcher is installed and I am logged in.

[extensions.log](https://github.com/Jeshibu/PlayniteExtensions/files/8969217/extensions.log)
[playnite.log](https://github.com/Jeshibu/PlayniteExtensions/files/8969218/playnite.log)

**Comment by Jeshibu** [comment]
Apparently I forgot to log that exception. My bad. Can you trigger the error again with this version of the plugin and then send me the logs again?
https://github.com/Jeshibu/PlayniteExtensions/releases/download/legacygames0.1.1/LegacyGamesLibrary_0_1_2.pext

**Comment by wolfrik17** [comment]
[extensions.log](https://github.com/Jeshibu/PlayniteExtensions/files/8971192/extensions.log)
[playnite.log](https://github.com/Jeshibu/PlayniteExtensions/files/8971194/playnite.log)

Here you go

**Comment by Jeshibu** [comment]
In your `%appdata%\legacy-games-launcher` folder there is a file named `app-state.json`. The plugin reads this for most of its data. In it, there is a `user.profile.downloads` property, that looks like this (mine is at the end of the file, yours might not be):
![image](https://user-images.githubusercontent.com/37979717/175432361-02da9c07-1c74-48c7-b93d-ebda012f6d39.png)

Could you share what yours looks like? The error is saying that the `downloads` property is empty, which is where all your game (bundle) purchases/entitlements are stored.

**Comment by wolfrik17** [comment]
I checked the file and there was no downloads section, it stopped after username, so I opened the Legacy launcher, downloaded a game and checked the file again and now my file looks just like yours, no more errors in playnite and it imported all my games perfectly. 

Seems like you need to download at least 1 game for that section to populate with all your owned games.

**Comment by Jeshibu** [comment]
Should be fixed now.
