### ISSUE TITLE
Launchbox Metadata - Database Never Initalizes and Cannot Search for Metadata

### ISSUE THREAD

**Issue by GumbyXGames** [Jeshibu/PlayniteExtensions#61]
When downloading the Launchbox Metadata Source add-on on a new install of Playnite, I cannot get the local database to initializes and as a result, cannot download metadata from Lunchbox This is an issue with the add-on as I do not have this issue with the GOG, Microsoft, Amazon, or Steam Metadata add-ons,.

I have downloaded the metadata.xml file both within the add-on and manually. Playnite is installed to the default folder. Something on the Launchbox database site may have changed and be the casuse of the problem.

**Comment by Jeshibu** [comment]
Will fix soon. For now, a workaround is opening `Metadata.xml` with a text editor and deleting the following string from it: `&#xC;`. then do the manual import again.

**Comment by GumbyXGames** [comment]
> Will fix soon. For now, a workaround is opening `Metadata.xml` with a text editor and deleting the following string from it: `&#xC;`. then do the manual import again.

That got it working. Appreciate the workaround.
