### ISSUE TITLE
Crashing my Playnite

### ISSUE THREAD

**Issue by livejamie** [Jeshibu/PlayniteExtensions#7]
This is the file playnite generated on the crash

[groupees.zip](https://github.com/Jeshibu/PlayniteExtensions/files/9034893/groupees.zip)

**Comment by Jeshibu** [comment]
Could you see if this fixes the problem?
Either way I'd be interested in the new logs to see what ended up being null.

https://github.com/Jeshibu/PlayniteExtensions/releases/download/groupees0.2/GroupeesLibrary_0_2_1.pext

**Comment by Jeshibu** [comment]
@livejamie did the above release solve the issue?
